<?php

/**
 * @file
 * Module used to find and correct missing derivatives of objects in Islandora.
 * 
 */

/*
 * Implementation of hook_menu().
 */
function islandora_derivatives_menu() {
  $items['admin/settings/islandora_derivatives'] = array(
    'title' => 'Islandora Derivatives',
    'description' => 'Admin page for Islandora Derivatives',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_derivatives_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/change'] = array(
    'page callback' => 'islandora_derivatives_change_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/addcollection'] = array(
    'page callback' => 'islandora_derivatives_add_collection_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/findmissing'] = array(
    'page callback' => 'islandora_derivatives_find_missing_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );  
  $items['admin/settings/islandora_derivatives/status'] = array(
     'page callback' => 'islandora_derivatives_search_status',
     'access arguments' => array('administer site configuration'),
     'type' => MENU_CALLBACK,
  );
   $items['admin/settings/islandora_derivatives/submit'] = array(
    'page callback' => 'islandora_derivatives_submit_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Form constructor for the islandora_derivatives form.
 * 
 * @param array $form_state
 *   The Drupal form state.
 * 
 * @see islandora_derivatives_menu()
 */
function islandora_derivatives_form($form_state) {
  module_load_include('inc', 'php_lib', 'Ahah');
  require_once("Stomp.php");
  drupal_add_css(drupal_get_path('module', 'islandora_derivatives') . '/css/islandora_derivatives.css');
    
  $tempstomp = variable_get('fedora_soap_url', 'http://localhost:8080/fedora/services/access?wsdl');
  preg_match('#\/\/(.*):#', $tempstomp, $matches);
  $defaultstomp = 'tcp://' . $matches[1] . ':61613';
  
  $namespaces = variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ');
  
  // Get all collections from Fedora
  $itql_query = 'select $child $title from <#ri> 
      where 
      ( 
        ( 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $parent_model <mulgara:is> <info:fedora/fedora-system:ContentModel-3.0> 
          ) 
        or 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <fedora-model:hasModel> $parent_model 
          and $parent_model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $child <fedora-model:state> <info:fedora/fedora-system:def/model#Active> 
          ) 
       ) 
      or 
        ( 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $parent_model <mulgara:is> <info:fedora/fedora-system:ContentModel-3.0> 
          ) 
        or 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <fedora-model:hasModel> $parent_model 
          and $parent_model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $child <fedora-model:state> <info:fedora/fedora-system:def/model#Active> 
          ) 
       )
     )
     and $child <fedora-model:label> $title
     order by $title asc';
  
  module_load_include('inc', 'fedora_repository', 'CollectionClass');
  $collectionClass = new CollectionClass();
  $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);
  $xml_set = simplexml_load_string($query_results);
  $collectionlist['default'] = '-- Select a collection --';
  
  // Grab the pids from the ITQL results if in the allowed namespaces
  foreach($xml_set->results->result as $result) {
    $pid = (string) $result->child->attributes()->uri;
    $label = (string) $result->title;
    
    preg_match('/info:fedora\/(.*):/', $pid, $matches);
    $objnamespace = $matches[1] . ':';
    
    $allowednames = explode(' ', trim($namespaces));
        
    if (in_array($objnamespace, $allowednames)) {
    $pid = str_replace('info:fedora/', '', $pid);
    $collectionlist[$pid] = $label . ' (' . $pid . ')';  
    }
  }
   
  $options['default'] = t('-- Select an option --');
  $options['all'] = t('All derivatives');
  $options['missing'] = t('Only missing derivatives');
  
  $form = array(
    '#title' => t('Islandora Derivatives'),
    '#prefix' => '<div id="islandora_derivatives">',
    '#suffix' => '</div>',
    '#action' => '/admin/settings/islandora_derivatives',
    'derivoptions' => array(
      '#type' => 'select',
      '#title' => t('Select an option of regenerating derivatives'),
      '#options' => $options,
      '#weight' => 1,
    ),
    'findmissing' => array(
      '#type' => 'checkbox',
      '#title' => t('Include all missing derivatives?'),
      '#weight' => 2,
      '#ahah' => array(
        'path' => 'admin/settings/islandora_derivatives/findmissing',
        'wrapper' => 'islandora_derivatives',
        'progress' => array(
          'type' => 'bar',
          'message' => t('Searching..'),
          'interval' => 1,
          'url' => '/admin/settings/islandora_derivatives/status'
        ),
      ),
    ),
    'collectionoptions' => array(
      '#type' => 'select',
      '#title' => t('Select a collection to recursively go through'),
      '#options' => $collectionlist,
      '#prefix' => '<div class="islandora_derivatives_collection_list">',
      '#suffix' => '</div>',
      '#weight' => 3,
    ),
    'collectionadd' => array(
      '#type' => 'image_button',
        '#src' => drupal_get_path('module', 'islandora_derivatives') . '/images/add.png', 
        '#ahah' => array(
          'event' => 'click',
          'path' => 'admin/settings/islandora_derivatives/addcollection',
          'wrapper' => 'islandora_derivatives',
        ),
      '#weight' => 4,
    ),
    'pidtextarea' => array(
      '#type' => 'textarea',
      '#title' => t('List of pids to be processed separated by commas'),
      '#description' => t('Allowed namespaces are: %namespaces',
          array(
          '%namespaces' => $namespaces,  
          )),
      '#weight' => 5,
    ),
    'submit' => array(
      '#type' => 'submit',
      '#name' => 'islandora_derivatives_form_submit_button',
      '#value' => t('Update Derivatives'),
      '#weight' => 6,
      '#ahah' => array(
          'event' => 'click',
          'path' => 'admin/settings/islandora_derivatives/submit',
          'wrapper' => 'islandora_derivatives',
        ),
    ),
    'advancedoptions' => array(
      '#type' => 'fieldset',
      '#title' => t('Advanced options'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#prefix' => '<div id="islandora_derivatives_stomp_url">',
      '#suffix' => '</div>',
      '#weight' => 7,
      'islandora_derivatives_stompurl' => array(
        '#type' => 'textfield',
        '#title' => t('Stomp URL'),
        '#default_value' => variable_get('islandora_derivatives_stompurl', $defaultstomp), 
        '#ahah' => array(
          'path' => 'admin/settings/islandora_derivatives/change',
          'wrapper' => 'islandora_derivatives_stomp_url',
          'keypress' => TRUE,
        ),
      )
    ),
  );     
  
  // Determine whether the current URL is able to connect to Stomp
  if (islandora_derivatives_stomp_avail(variable_get('islandora_derivatives_stompurl', $defaultstomp))) {
    $constatus = '<img src="' . url('misc/watchdog-ok.png') . '"/>'
          . t('Successfully connected to Stomp server at %stomp_url', 
          array(
            '%stomp_url' => variable_get('islandora_derivatives_stompurl', $defaultstomp)
          ));
  }
  else {
    $constatus = '<img src="'
          . url('misc/watchdog-error.png') . '"/> '
          . t('Unable to connect to Stomp server at %stomp_url', 
          array(
            '%stomp_url' => variable_get('islandora_derivatives_stompurl', $defaultstomp)
          ));
  }
  $form['advancedoptions']['stompcon'] = array(
    '#type' => 'item',
    '#value' => $constatus,
  );
  return $form; 
}

/**
 * AHAH callback that searches for and displays all the objects that are missing
 * derivatives.
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_find_missing_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
    
  if (!empty($form_state['post']['findmissing'])) {
    $checked = TRUE;
  }
  $pids = $form_state['post']['pidtextarea'];
  $derivoptions = $_POST['derivoptions'];
    
  if ($checked == FALSE && !empty($pids) && $form_state['storage']['missingderivs'] != 'NONE') {
    $pids = str_replace(',', ' ', $pids);
    foreach($form_state['storage']['missingderivs'] as $pid) {
      $pids = str_replace($pid, '', $pids);
    }
    $pids = trim($pids);
    
    // This allows for any other values present besides the missing derivs to be
    // retained and outputted. Allows for variable whitespacing inbetween the commas
    $pidoutput = explode(' ', $pids);
    foreach($pidoutput as $pidtext) {
      if (!empty($pidtext)) {
        if (empty($pidlist)) {
          $pidlist = $pidtext;
        }
        else {
          $pidlist .= ', ' . $pidtext;
        }
      }
    }
    $pids = $pidlist;
  }
  // Previous query resulted in no objects missing derivatives
  elseif ($form_state['storage']['missingderivs'] == 'NONE') {
    drupal_set_message(t('There are no objects with missing derivatives in the allowed namespaces!'));
  }
  // Search for objects missing derivatives
  else {
    if (!isset($form_state['storage']['missingderivs'])) {
      $itql_query = 'select $object from <#ri> where 
        $object <fedora-model:hasModel> $model
        and 
        (
        $object <fedora-rels-ext:isMemberOf> $member
        or
        $object <fedora-rels-ext:isMemberOfCollection> $collection
        )';
      module_load_include('inc', 'fedora_repository', 'CollectionClass');
      module_load_include('inc', 'fedora_repository', 'api/fedora_item');
      $collectionClass = new CollectionClass();
      $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);

      $xml_set = simplexml_load_string($query_results);
      $missingarray = array();
           
      foreach ($xml_set->results->result as $result) {
        $pid = $result->object->attributes()->uri;
        $pid = str_replace('info:fedora/', '', (string)$pid);
        
        preg_match('/(.*):/', $pid, $matches);
        $objnamespace = $matches[1] . ':';
        $allowednames = explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ')));

        if (in_array($objnamespace, $allowednames)) {
          $resultpids[] = $pid;
        }
      }
      
      // Used in updating the progress bar while searching takes place
      variable_set('islandora_derivatives_total_missing', count($resultpids));
      variable_set('islandora_derivatives_current_obj', 0);
      $allowedds = array(
        'DC' => 'DC',
        'MODS' => 'MODS',
        'RELS-INT' => 'RELS-INT',
        'RELS-EXT' => 'RELS-EXT',
        'POLICY' => 'POLICY',
        'TN' => 'TN',
        );
      $allowedmime = array(
        'gif' => 'image/gif',
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'raw' => 'image/raw',
        'tiff' => 'image/tiff',
        'tif' => 'image/tif',
        'x-raw' => 'image/x-raw',
      );
      
      foreach ($resultpids as $pid) {
        variable_set('islandora_derivatives_current_obj', variable_get('islandora_derivatives_current_obj', '1') + 1);
        $object = new Fedora_Item($pid);
        $missing = FALSE;
        
        
        $dslist = $object->get_datastreams_list_as_array();
        
        foreach ($dslist as $dslabel => $datastream) {
          if (!in_array($dslabel, $allowedds) && in_array($datastream['MIMEType'], $allowedmime)) {
            if ($datastream['label'] != 'thumbnail') {
              $tempthumb = $dslabel . '-tn.jpg';
              $tempjp2 = $dslabel . '.jp2';
                           
              if (!array_key_exists($tempjp2, $dslist) || !array_key_exists($tempthumb, $dslist)) {
                $missing = TRUE;
              }
            }
          }
        }
        
        if ($missing) {
            $missingarray[] = $pid;
            $object->forget();
          }
          else {
            $object->forget();
          }
      }
    }
    else {
     $missingarray = $form_state['storage']['missingderivs']; 
    }
    
    if (!empty($missingarray)) {
      foreach ($missingarray as $pid) {
        preg_match('/(.*):/', $pid, $matches);
        $objnamespace = $matches[1] . ':';
        $allowednames = explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ')));

        $derivs[] = $pid;
        if (!empty($pids)) {
          $intext = strpos($pid, $pids);
        }
        // Add to the pid textarea if doesn't already exist
        if ($intext !== true) {
          if (strlen($pids) != 0) {
            $pids .= ', ' . $pid;
          }
          else {
            $pids = $pid;
          }
        } 
      }
    }
  }
  
  if (!empty($missingarray)) {
    $form_state['storage']['missingderivs'] = $derivs;
  }
  else {
    // Needed so that the query doesn't get executed
    $form_state['storage']['missingderivs'] = 'NONE';
  }
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['pidtextarea']['#value'] = $pids;
  $form['findmissing']['#value'] = $checked;
  $form['derivoptions']['#value'] = $derivoptions;
    
  Ahah::respond($form);
  exit();
}

/**
 * AHAH callback for a user attempting to change the URL of the Stomp server
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_change_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  require_once('Stomp.php');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
     
  $form = array();
  if (!islandora_derivatives_stomp_avail($form_state['post']['islandora_derivatives_stompurl'])) {
    drupal_set_message(t("Connection to Stomp failed!"), error);
  }
  variable_set('islandora_derivatives_stompurl', $form_state['post']['islandora_derivatives_stompurl']);
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $data = theme('status_messages');
    if (isset($form)) {
      unset($form['#prefix'], $form['#suffix']);
      $form['advancedoptions']['islandora_derivatives_stompurl']['#value'] = variable_get('islandora_derivatives_stompurl', 'tcp://localhost:61613');
      $form['advancedoptions']['#collapsed'] = FALSE;
      $data .= drupal_render($form['advancedoptions']);
    }
    
    $javascript = drupal_add_js(NULL, NULL, 'header');
    $settings = call_user_func_array('array_merge_recursive', $javascript['setting']);
    unset($settings['ahah']['']);
    drupal_json(array(
      'status' => TRUE,
      'data' => $data,
      'settings' => $settings,
    ));
  exit();
}

/**
 * AHAH callback for a user adding a collection to the pid text area to be used
 * in regenerating derivatives.
 * 
 * @see islandora_pid_list_menu() 
 */
function islandora_derivatives_add_collection_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
  
  $pidselect = $_POST['collectionoptions'];
  $pids = $_POST['pidtextarea'];
  $checked = $_POST['findmissing'];
  
  $derivoptions = $_POST['derivoptions'];
  
  if ($pidselect == 'default') {
    drupal_set_message(t('No collection selected'), 'error');
  }
  else {
    // We need to walk through the selected collection to get all children of the
    // collection. Check to see if they already in the textarea.
    $itql_query = 'select $child from <#ri> where
    (
      walk (
        $parent <fedora-rels-ext:isMemberOfCollection> <info:fedora/'.$pidselect.'>
        and $child <fedora-rels-ext:isMemberOfCollection> $parent
      )
    or
      walk (
        $parent <fedora-rels-ext:isMemberOf> <info:fedora/'.$pidselect.'>
        and $child <fedora-rels-ext:isMemberOf> $parent
      )
    )';
    
    module_load_include('inc', 'fedora_repository', 'CollectionClass');
    $collectionClass = new CollectionClass();
    $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);
    $xml_set = simplexml_load_string($query_results);
        
    foreach($xml_set->results->result as $result) {
        $pid = (string) $result->child->attributes()->uri;
        preg_match('/info:fedora\/(.*):/', $pid, $matches);
        $objnamespace = $matches[1] . ':';
        $allowednames = explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ')));
        
        if (in_array($objnamespace, $allowednames)) {
          $pid = str_replace('info:fedora/', '', $pid);
          if (!empty($pids)) {
            $intext = strpos($pid, $pids);
          }
          
          // Add to the pid textarea if doesn't already exist
          if ($intext !== true) {
            if (strlen($pids) != 0) {
              $pids .= ', ' . $pid;
            }
            else {
              $pids = $pid;
            }
          }
        }
     }  
  }
 $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
 $form['pidtextarea']['#value'] = $pids;
 Ahah::respond($form);
 exit();
}
 
 /*
  * Determines whether the given URL results in a valid connection to Stomp.
  * 
  *  @param string $url
  *    The URL that the connection attempts to take place on.
  * 
  *  @throws Exception
  * 
  */
function islandora_derivatives_stomp_avail($url) {
  try {
    $stomp = new Stomp($url);
    $stomp->connect();
  } catch (Exception $e) {
    return false;
  }
  return true;
}

 /*
  * Used to update the percantage of the progress bar during searching.
  */
function islandora_derivatives_search_status() {
  $percentage = round((variable_get('islandora_derivatives_current_obj', '1') / variable_get('islandora_derivatives_total_missing', '1000')) * 100);
  drupal_json(array('percentage' => $percentage));
}

 /*
  *  Submit handler for the AHAH enabled button. Attempts to connect to Stomp
  *  and sends messages to the topic/islandora queue in order to regenerate
  * 
  *  @throws Exception
  * 
  */
function islandora_derivatives_submit_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  require_once('Stomp.php');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
  
  if (!empty($form_state['post']['findmissing'])) {
    $checked = TRUE;
  }
  
  $pids = $_POST['pidtextarea'];
  $derivoptions = $_POST['derivoptions'];   
  
  try {
    $stomp = new Stomp(variable_get('islandora_derivatives_stompurl', $_POST['islandora_derivatives_stompurl']));
    $stomp->connect();
  } catch (Exception $e) {
    drupal_set_message(t("Unable to start process as the connection to Stomp at %stomp_url failed!",
        array(
          '%stomp_url' => variable_get('islandora_derivatives_stompurl', $_POST['islandora_derivatives_stompurl']),
        )
    ), error);
    $failedcon = TRUE;
  }
  
  if (!$failedcon) {
    if ($derivoptions == 'all') {
      $message = 'regenerateDerivatives';
    }
    elseif ($derivoptions == 'missing') {
      $message = 'generateDerivatives';
    }
    else {
      drupal_set_message(t('You must select an option on how to regenerate derivatives'), 'error');
      $noderiv = TRUE;
    }
    
    if (!empty($pids) && $noderiv == FALSE) {
    $namespaces = explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ')));
    $derivpidlist = explode(',', $pids);

      foreach ($derivpidlist as $index => $pid) {
        $pid = trim($pid);
        $pidnamespace = substr($pid, 0, strpos($pid, ':') + 1);

        if (in_array($pidnamespace, $namespaces)) {
          $allowedderivs[] = $pid;
        }
        else {
          if (strlen($failedderivs) != 0) {
            $failedderivs .= ', ' . $pid;
          }
          else {
            $failedderivs = $pid;
          }
        }
      }
      if (!empty($allowedderivs)) {
        foreach($allowedderivs as $key => $value) {
          $headers['method'] = $message;
          $msgarray['pid'] = $value;          
          $stomp->send('/topic/islandora', json_encode($msgarray), $headers);
          $allowedoutput .= $value . " ";
        }         
      }
    }
    elseif (empty($pids)) {
      drupal_set_message(t('At least one PID must be entered in order to proceed'), 'error');
    }
    
    if (!empty($failedderivs)) {
      drupal_set_message(t('The following pids are not in the allowed namespaces and weren\'t processed: %failed',
          array(
            '%failed' => $failedderivs,
          )
      ), 'error');
    }
    if (!empty($allowedderivs)) {
      drupal_set_message(t('Microservices will begin regenerating derivatives for: %allowedderivs',
          array(
            '%allowedderivs' => trim($allowedoutput),
          )
          ));
      $pids = '';
    }
  }  
  
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['pidtextarea']['#value'] = $pids;
  $form['derivoptions']['#value'] = $derivoptions;
  $form['findmissing']['#value'] = $checked;
  Ahah::respond($form);
  exit();
}