<?php

/**
 * @file
 * Module used to find and correct missing derivatives of objects in Islandora.
 * 
 */

/*
 * Implementation of hook_menu().
 */
function islandora_derivatives_menu() {
  $items['admin/settings/islandora_derivatives'] = array(
    'title' => 'Islandora Derivatives',
    'description' => 'Admin page for Islandora Derivatives',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('islandora_derivatives_form'),
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/change'] = array(
    'page callback' => 'islandora_derivatives_change_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/addcollection'] = array(
    'page callback' => 'islandora_derivatives_add_collection_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/findmissing'] = array(
    'page callback' => 'islandora_derivatives_find_missing_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );  
  $items['admin/settings/islandora_derivatives/status'] = array(
     'page callback' => 'islandora_derivatives_search_status',
     'access arguments' => array('administer site configuration'),
     'type' => MENU_CALLBACK,
  );
  $items['admin/settings/islandora_derivatives/submit'] = array(
    'page callback' => 'islandora_derivatives_submit_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
   $items['admin/settings/islandora_derivatives/audioadd'] = array(
    'page callback' => 'islandora_derivatives_audio_add_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
   $items['admin/settings/islandora_derivatives/videoadd'] = array(
    'page callback' => 'islandora_derivatives_video_add_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/docadd'] = array(
    'page callback' => 'islandora_derivatives_doc_add_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  $items['admin/settings/islandora_derivatives/imageadd'] = array(
    'page callback' => 'islandora_derivatives_img_add_js',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}

/**
 * Form constructor for the islandora_derivatives form.
 * 
 * @param array $form_state
 *   The Drupal form state.
 * 
 * @see islandora_derivatives_menu()
 */
function islandora_derivatives_form($form_state) {
  module_load_include('inc', 'php_lib', 'Ahah');
  require_once("Stomp.php");
  drupal_add_css(drupal_get_path('module', 'islandora_derivatives') . '/css/islandora_derivatives.css');
  AHAH::get_ahah_js();
  
  
  $tempstomp = variable_get('fedora_soap_url', 'http://localhost:8080/fedora/services/access?wsdl');
  preg_match('#\/\/(.*):#', $tempstomp, $matches);
  $defaultstomp = 'tcp://' . $matches[1] . ':61613';
  
  $namespaces = variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ');
  
  // Get all collections from Fedora
  $itql_query = 'select $child $title from <#ri> 
      where 
      ( 
        ( 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $parent_model <mulgara:is> <info:fedora/fedora-system:ContentModel-3.0> 
          ) 
        or 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <fedora-model:hasModel> $parent_model 
          and $parent_model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $child <fedora-model:state> <info:fedora/fedora-system:def/model#Active> 
          ) 
       ) 
      or 
        ( 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $parent_model <mulgara:is> <info:fedora/fedora-system:ContentModel-3.0> 
          ) 
        or 
          ( 
          $child <fedora-model:hasModel> $model 
          and $model <fedora-model:hasModel> $parent_model 
          and $parent_model <mulgara:is> <info:fedora/islandora:collectionCModel> 
          and $child <fedora-model:state> <info:fedora/fedora-system:def/model#Active> 
          ) 
       )
     )
     and $child <fedora-model:label> $title
     order by $title asc';
  
  module_load_include('inc', 'fedora_repository', 'CollectionClass');
  $collectionClass = new CollectionClass();
  $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);
  $xml_set = simplexml_load_string($query_results);
  $collectionlist['default'] = '-- Select a collection --';
  
  // Grab the pids from the ITQL results if in the allowed namespaces
  foreach($xml_set->results->result as $result) {
    $pid = (string) $result->child->attributes()->uri;
    $label = (string) $result->title;
    
    preg_match('/info:fedora\/(.*):/', $pid, $matches);
    $objnamespace = $matches[1] . ':';
    
    $allowednames = explode(' ', trim($namespaces));
        
    if (in_array($objnamespace, $allowednames)) {
    $pid = str_replace('info:fedora/', '', $pid);
    $collectionlist[$pid] = $label . ' (' . $pid . ')';  
    }
  }
   
  $options['default'] = t('-- Select an option --');
  $options['all'] = t('Regenerate all derivatives');
  $options['missing'] = t('Generate missing derivatives');
  
  $form = array(
    '#title' => t('Islandora Derivatives'),
    '#prefix' => '<div id="islandora_derivatives">',
    '#suffix' => '</div>',
    '#action' => '/admin/settings/islandora_derivatives',
    'derivoptions' => array(
      '#type' => 'select',
      '#title' => t('Select an action for these PIDs'),
      '#options' => $options,
      '#weight' => 5,
    ),
    'collectionoptions' => array(
      '#type' => 'select',
      '#title' => t('Select PIDs from a collection'),
      '#options' => $collectionlist,
      '#prefix' => '<div class="islandora_derivatives_collection_list">',
      '#suffix' => '</div>',
      '#weight' => 2,
    ),
    'collectionadd' => array(
      '#type' => 'button',
      '#value' => t('Add PIDs to processing list?'),
      '#ahah' => array(
        'event' => 'click',
        'path' => 'admin/settings/islandora_derivatives/addcollection',
        'wrapper' => 'islandora_derivatives',
      ),
      '#weight' => 2,
    ),
    'pidtextarea' => array(
      '#type' => 'textarea',
      '#title' => t('List of pids to be processed separated by commas'),
      '#description' => t('Allowed namespaces are: %namespaces',
          array(
          '%namespaces' => $namespaces,  
          )),
      '#weight' => 4,
    ),
    'submit' => array(
      '#type' => 'submit',
      '#name' => 'islandora_derivatives_form_submit_button',
      '#value' => t('Update Derivatives'),
      '#weight' => 6,
      '#ahah' => array(
          'event' => 'click',
          'path' => 'admin/settings/islandora_derivatives/submit',
          'wrapper' => 'islandora_derivatives',
        ),
    ),
    'advancedoptions' => array(
      '#type' => 'fieldset',
      '#title' => t('Advanced options'),
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#prefix' => '<div id="islandora_derivatives_stomp_url">',
      '#suffix' => '</div>',
      '#weight' => 7,
      'islandora_derivatives_stompurl' => array(
        '#type' => 'textfield',
        '#title' => t('Stomp URL'),
        '#default_value' => variable_get('islandora_derivatives_stompurl', $defaultstomp), 
        '#ahah' => array(
          'path' => 'admin/settings/islandora_derivatives/change',
          'wrapper' => 'islandora_derivatives_stomp_url',
          'keypress' => TRUE,
        ),
      )
    ),
  );
    
  if (!isset($form_state['storage']['findmissing'])) {
    $form['findmissing'] = array(
      '#type' => 'button',
      '#value' => t('Search for all objects missing derivatives?'),
      '#weight' => 1,
      '#ahah' => array(
        'path' => 'admin/settings/islandora_derivatives/findmissing',
        'wrapper' => 'islandora_derivatives',
        'progress' => array(
          'type' => 'bar',
          'message' => t('Searching..'),
          'interval' => 1,
          'url' => '/admin/settings/islandora_derivatives/status'
        ),
      ),
    );
  }
  
  if (isset($form_state['storage']['missingderivs'])) {
    $form['missingderivfield'] = array(
      '#title' => t('Missing derivatives'),
      '#type' => 'fieldset',
      '#tree' => TRUE,
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#weight' => 1,
    );
    
    // Check the form state to see which fieldsets need to be created
    if (count($form_state['storage']['missingderivs']['aud']) > 0) {
      foreach($form_state['storage']['missingderivs']['aud'] as $pidtext) {
        if (!empty($pidtext)) {
          if (empty($pidlist)) {
            $pidlist = $pidtext;
          }
          else {
            $pidlist .= ', ' . $pidtext;
          }
        }
      }
      $form['missingderivfield']['audio'] = array(
        '#title' => t('Audio'),
        '#type' => 'fieldset',
        '#tree' => TRUE,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        'audtextarea' => array(
          '#type' => 'textarea',
          '#value' => $pidlist,
          '#disabled' => TRUE,
        ),
        'audioadd' => array(
          '#type' => 'checkbox',
          '#name' => 'islandora_derivatives_audio_box',
          '#title' => t('Add PIDs to processing list?'),
          '#weight' => 6,
          '#ahah' => array(
              'path' => 'admin/settings/islandora_derivatives/audioadd',
              'wrapper' => 'islandora_derivatives',
          ),
        ),
      );
    }
    
    if (count($form_state['storage']['missingderivs']['vid']) > 0) {
      foreach($form_state['storage']['missingderivs']['vid'] as $vidtext) {
        if (!empty($vidtext)) {
          if (empty($vidlist)) {
            $vidlist = $vidtext;
          }
          else {
            $vidlist .= ', ' . $vidtext;
          }
        }
      }
      
      $form['missingderivfield']['video'] = array(
        '#title' => t('Video'),
        '#type' => 'fieldset',
        '#tree' => TRUE,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        'vidtextarea' => array(
          '#type' => 'textarea',
          '#value' => $vidlist,
          '#disabled' => TRUE,
        ),
        'videoadd' => array(
          '#type' => 'checkbox',
          '#name' => 'islandora_derivatives_video_box',
          '#title' => t('Add PIDs to processing list?'),
          '#weight' => 6,
          '#ahah' => array(
              'path' => 'admin/settings/islandora_derivatives/videoadd',
              'wrapper' => 'islandora_derivatives',
          ),
        ),
      );
    }
    
    if (count($form_state['storage']['missingderivs']['doc']) > 0) {
      foreach($form_state['storage']['missingderivs']['doc'] as $doctext) {
        if (!empty($doctext)) {
          if (empty($doclist)) {
            $doclist = $doctext;
          }
          else {
            $doclist .= ', ' . $doctext;
          }
        }
      }
      $form['missingderivfield']['doc'] = array(
        '#title' => t('Documents'),
        '#type' => 'fieldset',
        '#tree' => TRUE,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        'doctextarea' => array(
          '#type' => 'textarea',
          '#value' => $doclist,
          '#disabled' => TRUE,
        ),
        'docadd' => array(
          '#type' => 'checkbox',
          '#name' => 'islandora_derivatives_doc_box',
          '#title' => t('Add PIDs to processing list?'),
          '#weight' => 6,
          '#ahah' => array(
              'path' => 'admin/settings/islandora_derivatives/docadd',
              'wrapper' => 'islandora_derivatives',
          ),
        ),  
      );
    }
    
    if (count($form_state['storage']['missingderivs']['img']) > 0) {
      foreach($form_state['storage']['missingderivs']['img'] as $imgtext) {
        if (!empty($imgtext)) {
          if (empty($imglist)) {
            $imglist = $imgtext;
          }
          else {
            $imglist .= ', ' . $imgtext;
          }
        }
      }
      $form['missingderivfield']['img'] = array(
        '#title' => t('Images'),
        '#type' => 'fieldset',
        '#tree' => TRUE,
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
        'imgtextarea' => array(
          '#type' => 'textarea',
          '#value' => $imglist,
          '#disabled' => TRUE,
        ),
        'imgadd' => array(
          '#type' => 'checkbox',
          '#name' => 'islandora_derivatives_img_box',
          '#title' => t('Add PIDs to processing list?'),
          '#weight' => 6,
          '#ahah' => array(
              'path' => 'admin/settings/islandora_derivatives/imageadd',
              'wrapper' => 'islandora_derivatives',
          ),
        ),  
      );
    }
  }
  
  // Determine whether the current URL is able to connect to Stomp
  if (islandora_derivatives_stomp_avail(variable_get('islandora_derivatives_stompurl', $defaultstomp))) {
    $constatus = '<img src="' . url('misc/watchdog-ok.png') . '"/>'
          . t('Successfully connected to Stomp server at %stomp_url', 
          array(
            '%stomp_url' => variable_get('islandora_derivatives_stompurl', $defaultstomp)
          ));
  }
  else {
    $constatus = '<img src="'
          . url('misc/watchdog-error.png') . '"/> '
          . t('Unable to connect to Stomp server at %stomp_url', 
          array(
            '%stomp_url' => variable_get('islandora_derivatives_stompurl', $defaultstomp)
          ));
  }
  $form['advancedoptions']['stompcon'] = array(
    '#type' => 'item',
    '#value' => $constatus,
  );
  return $form; 
}

/**
 * AHAH callback that searches for all the objects that are missing
 * derivatives.
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_find_missing_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
  
  $pids = $form_state['post']['pidtextarea'];
  $derivoptions = $_POST['derivoptions'];
      
  if (!empty($pids)) {
    $pids = str_replace(',', ' ', $pids);
    foreach($form_state['storage']['missingderivs'] as $pid) {
      $pids = str_replace($pid, '', $pids);
    }
    $pids = trim($pids);
    
    // This allows for any other values present besides the missing derivs to be
    // retained and outputted. Allows for variable whitespacing inbetween the commas
    $pidoutput = explode(' ', $pids);
    foreach($pidoutput as $pidtext) {
      if (!empty($pidtext)) {
        if (empty($pidlist)) {
          $pidlist = $pidtext;
        }
        else {
          $pidlist .= ', ' . $pidtext;
        }
      }
    }
    $pids = $pidlist;
  }
  // Search for objects missing derivatives
  else {
    if (!isset($form_state['storage']['missingderivs'])) {
      $itql_query = 'select $object from <#ri> where 
        $object <fedora-model:hasModel> $model
        and 
        (
        $object <fedora-rels-ext:isMemberOf> $member
        or
        $object <fedora-rels-ext:isMemberOfCollection> $collection
        )';
      module_load_include('inc', 'fedora_repository', 'CollectionClass');
      module_load_include('inc', 'fedora_repository', 'api/fedora_item');
      $collectionClass = new CollectionClass();
      $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);

      $xml_set = simplexml_load_string($query_results);
      $missingarray = array(
        'img' => array(),
        'doc' => array(),
        'vid' => array(),
        'aud' => array(),
      );
           
      foreach ($xml_set->results->result as $result) {
        $pid = $result->object->attributes()->uri;
        $pid = str_replace('info:fedora/', '', (string)$pid);
        
        preg_match('/(.*):/', $pid, $matches);
        $objnamespace = $matches[1] . ':';
        $allowednames = explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ')));

        if (in_array($objnamespace, $allowednames)) {
          $resultpids[] = $pid;
        }
      }
      
      // Used in updating the progress bar while searching takes place
      variable_set('islandora_derivatives_total_missing', count($resultpids));
      variable_set('islandora_derivatives_current_obj', 0);
      $allowedds = array(
        'DC' => 'DC',
        'MODS' => 'MODS',
        'RELS-INT' => 'RELS-INT',
        'RELS-EXT' => 'RELS-EXT',
        'POLICY' => 'POLICY',
        'TN' => 'TN',
        );
      $allowedimg = array(
        'jpeg' => 'image/jpeg',
        'png' => 'image/png',
        'tiff' => 'image/tiff',
        'tif' => 'image/tif',
        'jp2' => 'image/jp2',
        // Need to look at GIFs in microservices 'gif' => 'image/gif',
      );
      $alloweddoc = array(
        'pdf' => 'application/pdf',
        'ppt' => 'application/vnd.ms-powerpoint',
        'xls' => 'application/vnd.ms-excel',
        'word' => 'application/msword',
        'rtf' => 'text/rtf',
        'pptx' => 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'docx' => 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'xlsx' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      );
      $allowedaud = array(
        'mpeg' => 'audio/mpeg',
        'xwav' => 'audio/x-wave',
        'vndwave' => 'audio/vnd.wave',
      );
      $allowedvid = array(
        'mp4' => 'video/mp4',
        'mov' => 'video/quicktime',
        'wmv' => 'video/x-ms-wmv',
      );
      $combinedmimes = array_merge($allowedimg, $alloweddoc, $allowedaud, $allowedvid);
      // Go through and determine which objects are missing derivatives based 
      // upon the conditions in which microservices checks on.
      foreach ($resultpids as $pid) {
        variable_set('islandora_derivatives_current_obj', variable_get('islandora_derivatives_current_obj', '1') + 1);
        $object = new Fedora_Item($pid);
        $missing = FALSE;
        $rels = $object->get_datastream_dissemination('RELS-INT');
        
        if (!empty($rels)) {
          $xml = new SimpleXMLElement($rels); 
          $dslist = $object->get_datastreams_list_as_array();
          foreach ($dslist as $dsid => $datastream) { 
            if (!in_array($dsid, $allowedds)) {
               // Determine if it is one of our allowed MIMEs before continuing with processing.
              if (in_array($datastream['MIMEType'], $combinedmimes)) {
                $descriptions = $xml->xpath('rdf:Description[@rdf:about="info:fedora/'.$pid.'/'.$dsid.'"]');
                if ($descriptions) {
                  foreach ($descriptions as $result) {
                    if (in_array($datastream['MIMEType'], $allowedimg)) {
                      $jp2 = strpos($result->asXML(), 'hasJP2');
                      $TN = strpos($result->asXML(), 'hasThumbnail');
                      
                      if ($jp2 === false || $TN === false) {
                        $missing = TRUE;
                        if (!in_array($pid, $missingarray['img'])) {
                          $missingarray['img'][] = $pid;
                        }
                      }
                    } 
                    elseif (in_array($datastream['MIMEType'], $alloweddoc)) {
                      $swf = strpos($result->asXML(), 'hasSWF');
                      $TN = strpos($result->asXML(), 'hasThumbnail');
                      
                      if ($swf === false || $TN === false) {
                        $missing = TRUE;
                        if (!in_array($pid, $missingarray['doc'])) {
                          $missingarray['doc'][] = $pid;
                        }
                      }  
                    }
                    elseif (in_array($datastream['MIMEType'], $allowedaud)) {
                      $mp3 = strpos($result->asXML(), 'hasMP3');
                      $ogg = strpos($result->asXML(), 'hasOGG');
                      
                      if ($mp3 === false || $ogg === false) {
                        $missing = TRUE;
                        if (!in_array($pid, $missingarray['aud'])) {
                          $missingarray['aud'][] = $pid;
                        }
                      }
                    }
                    elseif (in_array($datastream['MIMEType'], $allowedvid)) {
                      $mp4 = strpos($result->asXML(), 'hasMP4');
                      $TN = strpos($result->asXML(), 'hasThumbnail');
                      
                      if ($mp4 === false || $TN === false) {
                        $missing = TRUE;
                        if (!in_array($pid, $missingarray['vid'])) {
                          $missingarray['vid'][] = $pid;
                        }
                      }
                    }
                  }
                }
                // Doesn't have an RDF about description for the pid and dsid combination.
                // Need to check if the datastream being passed in is a derivative.
                else {
                  $missing = TRUE; 
                  $dsidmime = $dslist[$dsid]['MIMEType'];
                  // Image
                  if (in_array($dsidmime, $allowedimg) && strpos($dsid, '-tn.jpg') === false && strpos($dsid, '.d.jp2') === false) {
                    // Check to see if this is a derivative, by 
                    if ($dsidmime == 'image/jp2') {
                      $origjp2 = preg_replace('/\.jp2/', '', $dsid);
                      $substrcount = 0;
                      foreach ($dslist as $key => $value) {
                        if (strpos($key, $origjp2) !== false) {
                          $substrcount++;
                        }
                      }
                      
                      if ($substrcount > 1) {
                         $missing = FALSE;
                      }
                    }
                  }
                  // Video
                  elseif (in_array($dsidmime, $allowedvid) && strpos($dsid, '-tn.jpg') === false && strpos($dsid, '.d.mp4') === false) {
                    if ($dsidmime == 'video/mp4') {
                      $origmp4 = preg_replace('/\.mp4/', '', $dsid);
                      $substrcount = 0;
                      foreach ($dslist as $key => $value) {
                        if (strpos($key, $origmp4) !== false) {
                          $substrcount++;
                        }
                      }
                      
                      if ($substrcount > 1) {
                         $missing = FALSE;
                      }
                    }
                  }
                  elseif (in_array($dsidmime, $allowedaud) && strpos($dsid, '.d.mp3') === false) {
                    if ($dsidmime == 'audio/mpeg') {
                      $origmp3 = preg_replace('/\.mp3/', '', $dsid);
                      $substrcount = 0;
                      foreach ($dslist as $key => $value) {
                        if (strpos($key, $origmp3) !== false) {
                          $substrcount++;
                        }
                      }
                      
                      if ($substrcount > 1) {
                        $missing = FALSE;
                      }
                    }
                  }
                  elseif (in_array($dsidmime, $alloweddoc)) {
                    if ($dsidmime == 'application/pdf') {
                      $origpdf = preg_replace('/\.pdf/', '', $dsid);
                      $substrcount = 0;
                      foreach ($dslist as $key => $value) {
                        if (strpos($key, $origpdf) !== false) {
                          $substrcount++;
                        }
                      }
                      
                      if ($substrcount > 1) {
                         $missing = FALSE;
                      }
                    }
                  }
                  if ($missing && strpos($dsid, '-tn.jpg') === false && strpos($dsid, '.d.jp2') === false && strpos($dsid, '.d.mp4') === false && strpos($dsid, '.d.mp3') === false) {
                    if (in_array($dsidmime, $alloweddoc)) {
                      if (!in_array($pid, $missingarray['doc'])) {
                        $missingarray['doc'][] = $pid;
                      }
                    }
                    elseif (in_array($dsidmime, $allowedimg)) {
                      if (!in_array($pid, $missingarray['img'])) {
                        $missingarray['img'][] = $pid;
                      }
                    }
                    elseif (in_array($dsidmime, $allowedvid)) {
                      if (!in_array($pid, $missingarray['vid'])) {
                        $missingarray['vid'][] = $pid;
                      }
                    }
                    elseif (in_array($dsidmime, $allowedaud)) {
                      if (!in_array($pid, $missingarray['aud'])) {
                        $missingarray['aud'][] = $pid;
                      }
                    }
                  }
                }
              }
            }
          }
        if ($missing) {
          $object->forget();
        }
        else {
          $object->forget();
        }
      }
    }
        
    if (empty($missingarray)) {
      drupal_set_message(t('There are no objects with missing derivatives in the allowed namespaces!'));
    }
    else {
      $form_state['storage']['missingderivs'] = $missingarray;
    }
    $form_state['storage']['findmissing'] = 'RAN';
    
    
    }
    
  }
    
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['findmissing']['#value'] = $checked;
  $form['derivoptions']['#value'] = $derivoptions;
    
  Ahah::respond($form);
  exit();
}

/**
 * AHAH callback for a user attempting to change the URL of the Stomp server
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_change_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  require_once('Stomp.php');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
     
  $form = array();
  if (!islandora_derivatives_stomp_avail($form_state['post']['islandora_derivatives_stompurl'])) {
    drupal_set_message(t("Connection to Stomp failed!"), error);
  }
  variable_set('islandora_derivatives_stompurl', $form_state['post']['islandora_derivatives_stompurl']);
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $data = theme('status_messages');
    if (isset($form)) {
      unset($form['#prefix'], $form['#suffix']);
      $form['advancedoptions']['islandora_derivatives_stompurl']['#value'] = variable_get('islandora_derivatives_stompurl', 'tcp://localhost:61613');
      $form['advancedoptions']['#collapsed'] = FALSE;
      $data .= drupal_render($form['advancedoptions']);
    }
    
    $javascript = drupal_add_js(NULL, NULL, 'header');
    $settings = call_user_func_array('array_merge_recursive', $javascript['setting']);
    unset($settings['ahah']['']);
    drupal_json(array(
      'status' => TRUE,
      'data' => $data,
      'settings' => $settings,
    ));
  exit();
}

/**
 * AHAH callback for a user adding a collection to the pid text area to be used
 * in regenerating derivatives.
 * 
 * @see islandora_pid_list_menu() 
 */
function islandora_derivatives_add_collection_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
  
  $pidselect = $_POST['collectionoptions'];
  $pids = $_POST['pidtextarea'];
  $checked = $_POST['findmissing'];
  $derivoptions = $_POST['derivoptions'];
  
  if ($pidselect == 'default') {
    drupal_set_message(t('No collection selected'), 'error');
  }
  else {
    // We need to walk through the selected collection to get all children of the
    // collection. Check to see if they already in the textarea.
    $itql_query = 'select $child from <#ri> where
    (
      walk (
        $parent <fedora-rels-ext:isMemberOfCollection> <info:fedora/'.$pidselect.'>
        and $child <fedora-rels-ext:isMemberOfCollection> $parent
      )
    or
      walk (
        $parent <fedora-rels-ext:isMemberOf> <info:fedora/'.$pidselect.'>
        and $child <fedora-rels-ext:isMemberOf> $parent
      )
    )';
    
    module_load_include('inc', 'fedora_repository', 'CollectionClass');
    $collectionClass = new CollectionClass();
    $query_results = $collectionClass->getRelatedItems(NULL, $itql_query);
    $xml_set = simplexml_load_string($query_results);
        
    foreach($xml_set->results->result as $result) {
        $pid = (string) $result->child->attributes()->uri;
        preg_match('/info:fedora\/(.*):/', $pid, $matches);
        $objnamespace = $matches[1] . ':';
        $allowednames = explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ')));
        
        if (in_array($objnamespace, $allowednames)) {
          $pid = str_replace('info:fedora/', '', $pid);
          if (!empty($pids)) {
            $intext = strpos($pid, $pids);
          }
          
          // Add to the pid textarea if doesn't already exist
          if ($intext !== true) {
            if (strlen($pids) != 0) {
              $pids .= ', ' . $pid;
            }
            else {
              $pids = $pid;
            }
          }
        }
     }  
  }
 $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
 $form['pidtextarea']['#value'] = $pids;
 Ahah::respond($form);
 exit();
}
 
 /*
  * Determines whether the given URL results in a valid connection to Stomp.
  * 
  *  @param string $url
  *    The URL that the connection attempts to take place on.
  * 
  *  @throws Exception
  * 
  */
function islandora_derivatives_stomp_avail($url) {
  try {
    $stomp = new Stomp($url);
    $stomp->connect();
  } catch (Exception $e) {
    return false;
  }
  return true;
}

 /*
  * Used to update the percantage of the progress bar during searching.
  */
function islandora_derivatives_search_status() {
  $percentage = round((variable_get('islandora_derivatives_current_obj', '1') / variable_get('islandora_derivatives_total_missing', '1000')) * 100);
  drupal_json(array('percentage' => $percentage));
}

 /*
  *  Submit handler for the AHAH enabled button. Attempts to connect to Stomp
  *  and sends messages to the topic/islandora queue in order to regenerate
  * 
  *  @throws Exception
  * 
  */
function islandora_derivatives_submit_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  require_once('Stomp.php');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
  
  if (!empty($form_state['post']['findmissing'])) {
    $checked = TRUE;
  }
  
  $pids = $_POST['pidtextarea'];

  $derivoptions = $_POST['derivoptions'];   
  
  try {
    $stomp = new Stomp(variable_get('islandora_derivatives_stompurl', $_POST['islandora_derivatives_stompurl']));
    $stomp->connect();
  } catch (Exception $e) {
    drupal_set_message(t("Unable to start process as the connection to Stomp at %stomp_url failed!",
        array(
          '%stomp_url' => variable_get('islandora_derivatives_stompurl', $_POST['islandora_derivatives_stompurl']),
        )
    ), error);
    $failedcon = TRUE;
  }
  
  if (!$failedcon) {
    if ($derivoptions == 'all') {
      $message = 'regenerateDerivatives';
    }
    elseif ($derivoptions == 'missing') {
      $message = 'generateDerivatives';
    }
    else {
      drupal_set_message(t('You must select an option on how to regenerate derivatives'), 'error');
      $noderiv = TRUE;
      $failed = TRUE;
    }
    
    if (!empty($pids) && $noderiv == FALSE) {
    $namespaces = explode(' ', trim(variable_get('fedora_pids_allowed', 'default: demo: changeme: islandora: ilives: islandora-book: books: newspapers: ')));
    $derivpidlist = explode(',', $pids);

      foreach ($derivpidlist as $index => $pid) {
        $pid = trim($pid);
        $pidnamespace = substr($pid, 0, strpos($pid, ':') + 1);

        if (in_array($pidnamespace, $namespaces)) {
          $allowedderivs[] = $pid;
        }
        else {
          if (strlen($failedderivs) != 0) {
            $failedderivs .= ', ' . $pid;
          }
          else {
            $failedderivs = $pid;
          }
        }
      }
      if (!empty($allowedderivs)) {
        foreach($allowedderivs as $key => $value) {
          $headers['method'] = $message;
          $msgarray['pid'] = $value;          
          $stomp->send('/topic/islandora', json_encode($msgarray), $headers);
          $allowedoutput .= $value . " ";
          
          if (isset($form_state['storage']['missingderivs'])) {
            // Search for stored value and remove if found
            foreach ($form_state['storage']['missingderivs'] as $key => $type) {
              $pidkey = array_search($pid, $form_state['storage']['missingderivs'][$key]);

              if ($pidkey !== 0) {
                unset($form_state['storage']['missingderivs'][$key][$pidkey]);
              }
            }
          }  
        }         
      }
    }
    elseif (empty($pids)) {
      drupal_set_message(t('At least one PID must be entered in order to proceed'), 'error');
      $failed = TRUE;
    }
    
    if (!empty($failedderivs)) {
      drupal_set_message(t('The following pids are not in the allowed namespaces and weren\'t processed: %failed',
          array(
            '%failed' => $failedderivs,
          )
      ), 'error');
    }
    if (!empty($allowedderivs)) {
      drupal_set_message(t('Microservices will begin regenerating derivatives for: %allowedderivs',
          array(
            '%allowedderivs' => trim($allowedoutput),
          )
          ));
      $pids = '';
    }
  }  
  
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['derivoptions']['#value'] = $derivoptions;
  if ($failed) {
    $form['pidtextarea']['#value'] = $pids;
  }
  Ahah::respond($form);
  exit();
}

/**
 * AHAH callback that adds or removes all missing audio objects to the textarea
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_audio_add_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
  
  if (!empty($form_state['post']['findmissing'])) {
    $checked = TRUE;
  }
  $form_state['storage']['findmissing'] = 'NOPE';
  
  $pids = $form_state['post']['pidtextarea'];
  $derivoptions = $_POST['derivoptions'];
  
  if ($form_state['post']['islandora_derivatives_audio_box'] == 1) {
    $form_state['storage']['derivboxes']['audio'] = 1;  
  }
  else {
    $form_state['storage']['derivboxes']['audio'] = 0;  
  }
  
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['derivoptions']['#value'] = $derivoptions;
   
  // Remember the user's checkboxes
  if (isset($form_state['storage']['derivboxes'])) {
    foreach ($form_state['storage']['derivboxes'] as $key => $value) {
      $form['missingderivfield'][$key][$key.'add']['#value'] = $value;
    }
  }
  
  $audpidsarray = explode(' ', str_replace(',', '', $form['missingderivfield']['audio']['audtextarea']['#value']));
  $curpids = trim($form_state['post']['pidtextarea']);
  
  if ($form_state['post']['islandora_derivatives_audio_box'] == 1) {
    $form['missingderivfield']['audio']['audioadd']['#value'] = 1;
      
    foreach ($audpidsarray as $audpid) {
        $intext = strpos($curpids, $audpid);
          
        // Add to the pid textarea if doesn't already exist
        if ($intext === false || empty($curpids)) {
          if (strlen($curpids) != 0) {
            $curpids .= ', ' . $audpid;
          }
          else {
            $curpids = $audpid;
          }
        }
      }
  }
  else {
    $curpids = str_replace(',', ' ', $curpids);
    foreach ($audpidsarray as $audpid) {
      $curpids = str_replace($audpid, '', $curpids);
    }
    $curpids = trim($curpids);
    
    // This allows for any other values present besides the missing derivs to be
    // retained and outputted. Allows for variable whitespacing inbetween the commas
    $pidoutput = explode(' ', $curpids);
    foreach($pidoutput as $pidtext) {
      if (!empty($pidtext)) {
        if (empty($pidlist)) {
          $pidlist = $pidtext;
        }
        else {
          $pidlist .= ', ' . $pidtext;
        }
      }
    }
    $curpids = $pidlist;
  }
  $form['pidtextarea']['#value'] = $curpids;
  Ahah::respond($form);
  exit();
}

/**
 * AHAH callback that adds or removes all missing video objects to the textarea
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_video_add_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
 
  if (!empty($form_state['post']['findmissing'])) {
    $checked = TRUE;
  }
  $form_state['storage']['findmissing'] = 'NOPE';
  $pids = $form_state['post']['pidtextarea'];
  $derivoptions = $_POST['derivoptions'];
  
  if ($form_state['post']['islandora_derivatives_video_box'] == 1) {
    $form_state['storage']['derivboxes']['video'] = 1;  
  }
  else {
    $form_state['storage']['derivboxes']['video'] = 0;  
  }
  
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['derivoptions']['#value'] = $derivoptions;
  $form['missingderivfield']['video']['#collapsed'] = FALSE;
  
  // Remember the user's checkboxes
  if (isset($form_state['storage']['derivboxes'])) {
    foreach ($form_state['storage']['derivboxes'] as $key => $value) {
      $form['missingderivfield'][$key][$key.'add']['#value'] = $value;
    }
  }
  
  $vidpidsarray = explode(' ', str_replace(',', '', $form['missingderivfield']['video']['vidtextarea']['#value']));
  $curpids = trim($form_state['post']['pidtextarea']);
  
  if ($form_state['post']['islandora_derivatives_video_box'] == 1) {
    $form['missingderivfield']['video']['videoadd']['#value'] = 1;
        
    foreach ($vidpidsarray as $vidpid) {
        $intext = strpos($curpids, $vidpid);
          
        // Add to the pid textarea if doesn't already exist
        if ($intext === false || empty($curpids)) {
          if (strlen($curpids) != 0) {
            $curpids .= ', ' . $vidpid;
          }
          else {
            $curpids = $vidpid;
          }
        }
      }
  }
  else {
   $curpids = str_replace(',', ' ', $curpids);
    foreach ($vidpidsarray as $vidpid) {
      $curpids = str_replace($vidpid, '', $curpids);
    }
    $curpids = trim($curpids);
    
    // This allows for any other values present besides the missing derivs to be
    // retained and outputted. Allows for variable whitespacing inbetween the commas
    $pidoutput = explode(' ', $curpids);
    foreach($pidoutput as $pidtext) {
      if (!empty($pidtext)) {
        if (empty($pidlist)) {
          $pidlist = $pidtext;
        }
        else {
          $pidlist .= ', ' . $pidtext;
        }
      }
    }
    $curpids = $pidlist;
  }
        
  $form['pidtextarea']['#value'] = $curpids;
  Ahah::respond($form);
  exit();
}

/**
 * AHAH callback that adds or removes all missing document objects to the textarea
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_doc_add_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
 
  if (!empty($form_state['post']['findmissing'])) {
    $checked = TRUE;
  }
  $form_state['storage']['findmissing'] = 'NOPE';
  $pids = $form_state['post']['pidtextarea'];
  $derivoptions = $_POST['derivoptions'];
  
  if ($form_state['post']['islandora_derivatives_doc_box'] == 1) {
    $form_state['storage']['derivboxes']['doc'] = 1;  
  }
  else {
    $form_state['storage']['derivboxes']['doc'] = 0;  
  }
  
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['derivoptions']['#value'] = $derivoptions;
  $form['missingderivfield']['doc']['#collapsed'] = FALSE;
  
  // Remember the user's checkboxes
  if (isset($form_state['storage']['derivboxes'])) {
    foreach ($form_state['storage']['derivboxes'] as $key => $value) {
      $form['missingderivfield'][$key][$key.'add']['#value'] = $value;
    }
  }
  
  $docpidsarray = explode(' ', str_replace(',', '', $form['missingderivfield']['doc']['doctextarea']['#value']));
  $curpids = trim($form_state['post']['pidtextarea']);
  
  if ($form_state['post']['islandora_derivatives_doc_box'] == 1) {
    $form['missingderivfield']['doc']['docadd']['#value'] = 1;
        
    foreach ($docpidsarray as $docpid) {
        $intext = strpos($curpids, $docpid);
          
        // Add to the pid textarea if doesn't already exist
        if ($intext === false || empty($curpids)) {
          if (strlen($curpids) != 0) {
            $curpids .= ', ' . $docpid;
          }
          else {
            $curpids = $docpid;
          }
        }
      }
  }
  else {
   $curpids = str_replace(',', ' ', $curpids);
    foreach ($docpidsarray as $docpid) {
      $curpids = str_replace($docpid, '', $curpids);
    }
    $curpids = trim($curpids);
    
    // This allows for any other values present besides the missing derivs to be
    // retained and outputted. Allows for variable whitespacing inbetween the commas
    $pidoutput = explode(' ', $curpids);
    foreach($pidoutput as $pidtext) {
      if (!empty($pidtext)) {
        if (empty($pidlist)) {
          $pidlist = $pidtext;
        }
        else {
          $pidlist .= ', ' . $pidtext;
        }
      }
    }
    $curpids = $pidlist;
  }
        
  $form['pidtextarea']['#value'] = $curpids;
  Ahah::respond($form);
  exit();
}

/**
 * AHAH callback that adds or removes all missing image objects to the textarea
 * 
 * @see islandora_derivatives_menu() 
 */
function islandora_derivatives_img_add_js() {
  module_load_include('inc', 'php_lib', 'Ahah');
  list($form_id, $form_build_id, $form, $form_state) = Ahah::getFormInfo();
 
  if (!empty($form_state['post']['findmissing'])) {
    $checked = TRUE;
  }
  $form_state['storage']['findmissing'] = 'NOPE';
  $pids = $form_state['post']['pidtextarea'];
  $derivoptions = $_POST['derivoptions'];
  
  if ($form_state['post']['islandora_derivatives_img_box'] == 1) {
    $form_state['storage']['derivboxes']['img'] = 1;  
  }
  else {
    $form_state['storage']['derivboxes']['img'] = 0;  
  }
  
  $form = Ahah::rebuildForm($form_id, $form_build_id, $form, $form_state);
  $form['derivoptions']['#value'] = $derivoptions;
  $form['missingderivfield']['img']['#collapsed'] = FALSE;
  
  // Remember the user's checkboxes
  if (isset($form_state['storage']['derivboxes'])) {
    foreach ($form_state['storage']['derivboxes'] as $key => $value) {
      $form['missingderivfield'][$key][$key.'add']['#value'] = $value;
    }
  }
  
  $imgpidsarray = explode(' ', str_replace(',', '', $form['missingderivfield']['img']['imgtextarea']['#value']));
  $curpids = trim($form_state['post']['pidtextarea']);
  
  if ($form_state['post']['islandora_derivatives_img_box'] == 1) {
    $form['missingderivfield']['img']['imgadd']['#value'] = 1;
        
    foreach ($imgpidsarray as $imgpid) {
        $intext = strpos($curpids, $imgpid);
          
        // Add to the pid textarea if doesn't already exist
        if ($intext === false || empty($curpids)) {
          if (strlen($curpids) != 0) {
            $curpids .= ', ' . $imgpid;
          }
          else {
            $curpids = $imgpid;
          }
        }
      }
  }
  else {
   $curpids = str_replace(',', ' ', $curpids);
    foreach ($imgpidsarray as $imgpid) {
      $curpids = str_replace($imgpid, '', $curpids);
    }
    $curpids = trim($curpids);
    
    // This allows for any other values present besides the missing derivs to be
    // retained and outputted. Allows for variable whitespacing inbetween the commas
    $pidoutput = explode(' ', $curpids);
    foreach($pidoutput as $pidtext) {
      if (!empty($pidtext)) {
        if (empty($pidlist)) {
          $pidlist = $pidtext;
        }
        else {
          $pidlist .= ', ' . $pidtext;
        }
      }
    }
    $curpids = $pidlist;
  }
        
  $form['pidtextarea']['#value'] = $curpids;
  Ahah::respond($form);
  exit();
}

